name: MacOS Spack Build

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-macos
  cancel-in-progress: true

jobs:
  MacOS-Clang:
    name: Apple Clang@17.0
    runs-on: macos-latest
    # env: {CXXFLAGS: "-fno-operator-names -Werror -Wall -Wextra -Wpedantic -Wnull-dereference -Wfloat-conversion -Wshadow -Woverloaded-virtual"}
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: no-mpi / particles OFF
          spec: "erf~mpi+particles"
        - name: no-mpi / particles ON
          spec: "erf~mpi~particles "
        - name: mpi / particles OFF
          spec: "erf+mpi+particles"
        - name: mpi / particles ON
          spec: "erf+mpi~particles"

    steps:

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup Spack
      uses: spack/setup-spack@v2
      with:
        path: ${{ github.workspace }}/spack_install_dir

    - name: Cache Spack downloads
      uses: actions/cache@v4
      with:
        path: |
          ~/.spack/cache
          ${{ github.workspace }}/spack_install_dir/var/spack/cache
        key: spack-cache-${{ runner.os }}-${{ hashFiles('**/package.py', '**/spack.yaml') }}
        restore-keys: |
          spack-cache-${{ runner.os }}-

    - name: Build ERF (${{ matrix.spec }})
      shell: bash
      run: |
        set -euxo pipefail
        echo ${{ github.workspace }}
        echo ${{ runner.workspace }}
        . ${{ github.workspace }}/spack_install_dir/share/spack/setup-env.sh
        spack env create -d ./.env
        spack -e ./.env add ${{ matrix.spec }}
        spack -e ./.env concretize -f
        spack -e ./.env install -j $(sysctl -n hw.ncpu)
